# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0005_auto_20170822_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deep_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.deepURL')),
            ],
        ),
    ]
