# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
