# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deepurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
