# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170815_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
