# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170816_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
