# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170816_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepurl',
            name='Url',
            field=models.CharField(max_length=254, validators=[shortener.validators.validate_Url, shortener.validators.validate_dot_com]),
        ),
    ]
